### ISSUE TITLE
fix pls

### ISSUE THREAD

**Issue by zooloogorbonos** [phanx-wow/HandyNotes_FieldPhotographer#1]
fix pls
Mount Indefatigable ( Kun-Lai 44.49 )

**Comment by Phanx** [comment]
Is the achievement actually unobtainable at the coordinates used in the addon?

I don't currently have an active subscription, so I can't verify, but I'm about 99% certain that I used my own addon while getting the achievement, in which case I'd have noticed if I was standing on the icon but couldn't get achievement credit.
