### ISSUE TITLE
Error since new Patch being updated Tuesday night to 7.35

### ISSUE THREAD

**Issue by Mindlessgalaxy** [phanx-wow/HandyNotes_FieldPhotographer#2]
Here is what looks like a simple error?  Maybe I shouldn't have said that, but I do really hope it is something you could even instruct me how to quickly fix please?

US English Client Oceanic Realm Nagrand Alliance Level 101 Rogue Night Elf.  On logging in and reloading this error occurs _**(and if I open map and try select a zone it always defaults back to the map of where I am within seconds.  So not able to look anywhere but where I currently am/ This is now playing up all the time so I assume not your add on but Mapster regarding the zooming out of zone etc otherwise the error still stands as with or without Mapster I have the fault and no icons either anymore)**_.  If I disable this add on I don't have any issue, but I want the field photographer add on to complete the Achieve please?  As far as I know it is the only good one if not the only one out there and you are awesome with all your add ons.  I am also using the add on Mapster, but this was only a problem after the new patch like always happens.

10x HandyNotes_FieldPhotographer\Addon.lua:472: Usage: UnitBuff("unit", [index] or ["name", "rank"][, "filter"])
[C]: in function `UnitBuff'
HandyNotes_FieldPhotographer\Addon.lua:472: in function <HandyNotes_FieldPhotographer\Addon.lua:469>
(tail call): ?

Locals:
(*temporary) = "player"
(*temporary) = nil

Thanks heaps and if you need anything more please do not  hesitate to ask and I will do what I can ASAP.

**Comment by Ookami313** [comment]
Greetings. I'm getting basically the same error as above as well after the update to 7.3.5, however my locals are displaying differently. Figured I'd add mine to this bug report as well just in case. Thanks.

Version 7.1.0.0

Date: 2018-01-17 19:53:02
ID: 2
Error occured in: Global
Count: 1
Message: ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua line 472:
   Usage: UnitBuff("unit", [index] or ["name", "rank"][, "filter"])
Debug:
   (tail call): ?
   [C]: ?
   [C]: UnitBuff()
   ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:472:
      ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:469
   (tail call): ?
Locals:
(*temporary) = "UPDATE_OVERRIDE_ACTIONBAR"
(*temporary) = "UPDATE_OVERRIDE_ACTIONBAR"
(*temporary) = <function> defined =[C]:-1

AddOns:

**Comment by hugalafutro** [comment]
same here, report @ https://pastebin.com/aCsrpVH0

**Comment by Fraktyl** [comment]
Edit line 249 in the Addon.lua file.

Change the number to 181765.  They removed the Mark I camera and changed it to a different spellID.

The line will look like:
(GetSpellInfo(181765)),

Seems to have fixed it for me.

For the map snapping back to the original zone, that's Collect Me and not this addon.  Author of that is aware of the issue and looking into it.

**Comment by Ookami313** [comment]
@Fraktyl That seems to have fixed the issue. Thanks.

**Comment by Mindlessgalaxy** [comment]
Thanks  @Fraktyl that is so awesome and really appreciated.  Made my day....
