### ISSUE TITLE
Patch 8.0.1 Bug

### ISSUE THREAD

**Issue by chelpixie** [phanx-wow/HandyNotes_FieldPhotographer#4]
Message: ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:447: attempt to call global 'GetMapContinents' (a nil value)
Time: Thu Jul 19 16:41:08 2018
Count: 1
Stack: ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:447: attempt to call global 'GetMapContinents' (a nil value)
...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:447: in function <...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:427>
(tail call): ?

Locals: self = <unnamed> {
 0 = <userdata>
 PLAYER_LOGIN = <function> defined @Interface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:427
 CRITERIA_UPDATE = <function> defined @Interface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:490
 db = <table> {
 }
 UPDATE_OVERRIDE_ACTIONBAR = <function> defined @Interface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:469
}
faction = "Alliance"
HereBeDragons = <table> {
 mapData = <table> {
 }
 callbacks = <table> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 transforms = <table> {
 }
 microDungeons = <table> {
 }
 UnregisterCallback = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 mapToID = <table> {
 }
 eventFrame = <unnamed> {
 }
 continentZoneMap = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMapContinents' (a nil value)"
HandyNotes = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:398
 GetContinentZoneList = <function> defined @Interface\AddOns\HandyNotes\HandyNotes.lua:221
 GetMapFiletoMapID = <function> defined @Interface\AddOns\HandyNotes\HandyNotes.lua:253
 Enable = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:325
 RegisterChatCommand = <function> defined @Interface\AddOns\Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 EnableModule = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 plugins = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface\AddOns\Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 Printf = <function> defined @Interface\AddOns\Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 OnProfileChanged = <function> defined @Interface\AddOns\HandyNotes\HandyNotes.lua:648
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 UpdateMinimapPlugin = <function> defined @Interface\AddOns\HandyNotes\HandyNotes.lua:420
 name = "HandyNotes"
 IsEnabled = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 UpdateWorldMapPlugin = <function> defined @Interface\AddOns\HandyNotes\HandyNotes.lua:407
 baseName = "HandyNotes"
 OnDisable = <function> defined @Interface\AddOns\HandyNotes\HandyNotes.lua:638
 OnEnable = <function> defined @Interface\AddOns\HandyNotes\HandyNotes.lua:625
 RegisterMessage = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 GetArgs = <function> defined @Interface\AddOns\Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Interface\AddOns\Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OnInitialize = <function> defined @Interface\AddOns\HandyNotes\HandyNotes.lua:607
 UpdatePluginMap = <function> defined @Interface\AddOns

**Comment by Qwers** [comment]
Date: 2018-07-20 18:18:55
ID: 17
Error occured in: Global
Count: 1
Message: ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua line 446:
   Cannot find a library instance of "HereBeDragons-1.0".
Debug:
   [C]: ?
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:446:
      ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:427
   (tail call): ?
Locals:

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  NPCScanOverlay, v7.3.0.1
  Ace3, v
  ACP, vr257 
  AdvancedInterfaceOptions, v1.2.4
  AllTheThings, v1.6.4a
  AnnounceInterrupts, v1.6i
  AtlasLoot, vv8.07.13
  AtlasLootBurningCrusade, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  Auctionator, v5.0.3
  AuctionatorMiniFeatures, v6.2v1-release
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v8.0.0
  BagnonScrap, v18
  Bartender4, v4.8.1
  BattlePetBreedID, vr170
  CanIMogIt, v8.0.0v1.9
  Configator, v5.1.DEV.431(/embedded)
  CTATracker, v
  DBMCore, v8.0.0-7-g3e50de67d
  DBMCountPackHoTS, v1.5
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r103
  EasyCopy, v5.0.1
  ExRT, v3930
  FixGroups, v1.4.1
  Gatherer, v7.3.1
  GuildNewsFilter, v1.1.0
  HandyNotes, vr301
  HandyNotesArgus, v0.20.0
  HandyNotesAzerothsTopTunes, vv1.2.1
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesFieldPhotographer, v7.3.5.0
  HandyNotesHallowsEnd, vv1.2.8-1-g81b70ff
  HandyNotesHigherLearning, v7.3.5.0
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesLunarFestival, vv1.4.5-1-gd4eec9d
  HandyNotesSummerFestival, vv1.4.2
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessIsleChests, v1.19
  HandyNotesTimelessTreasures, v1.0.7
  HandyNotesWellRead, v7.3.5.0
  LegendaryProgressTracker, v0.3.12
  LegionInvasionTimer, vv8.0.0
  LibExtraTip, v5.12.DEV.435(/embedded)
  LootAppraiser, v2018.v1.8.2
  LootAppraiserChallenge, v2018.v1.3.16
  MacroToolkit, vv7.3.0.2
  Masque, v8.0.0
  MasterPlanA, vA
  MaxCam, vv2.1.4
  MythicPlusTimer, v2.0-Alpha-1
  NPCScan, v8.0.1.2
  Oilvl, v6.7.37
  Omen, v3.2.0
  Overachiever, v1.0.0
  ParagonReputation, v1.19
  Pawn, v2.2.20
  PetTracker, v7.3.0
  PetTrackerBreeds, v7.3.0
  PetTrackerJournal, v7.3.0
  PetTrackerSwitcher, v7.3.0
  PetTrackerUpgrades, v7.3.0
  Postal, vv3.6.0
  Quartz, v3.4.0-3-g65bcdc4
  RaiderIO, v8.0.1 (v201807200600)
  RaiderIODBEUH, v
  RaidFrameReSizer, v
  Rarity, v1.0 (r658-alpha)
  RarityOptions, v
  RCLootCouncil, v2.8.0
  RealmHopAssist, vr02 beta
  RelicInspector, v3.0
  SavedInstances, v8.0.1-3-g531a3fd
  Scrap, v13.6
  ShadowedUnitFrames, vv4.2.0-1-g66d7e47
  Simulationcraft, v1.10.1
  Skada, v1.7.3
  SlideBar, v7.3.1 (<%codename%>)
  StrataFix, vr61
  TheUndermineJournal, v5.4.20180717
  TidyPlates, v6.18.11
  TidyPlatesBlizzardPlates, v1.5
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  Titan, v5.13.1.70300
  TitanBag, v5.13.1.70300
  TitanClock, v5.13.1.70300
  TitanGold, v5.13.1.70300
  TitanLocation, v5.13.1.70300
  TitanLootType, v5.13.1.70300
  TitanPerformance, v5.13.1.70300
  TitanRepair, v5.13.1.70300
  TitanVolume, v5.13.1.70300
  TitanXP, v5.13.1.70300
  TokenPrice, v1.3.1
  TomTom, vv80001-1.0.2-beta
  TradeSkillMaster, vv3.6.45
  TradeSkillMasterAccounting, vv3.0.22
  TradeSkillMasterAppHelper, vv3.0.5
  TradeSkillMasterAuctionDB, vv3.1.20
  TradeSkillMasterAuctioning, vv3.0.17
  TradeSkillMasterCrafting, vv3.2.8
  TradeSkillMasterMailing, vv3.0.19
  TradeSkillMasterShopping, vv3.4.9
  WeakAuras, v2.6.0-3-g4fc4ee6
  WorldQuestGroupFinder, v0.27
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=d8b)

**Comment by Enigma-TL** [comment]
Getting same as others.

Date: 2018-07-21 18:42:01
ID: 18
Error occured in: Global
Count: 1
Message: ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua line 446:
   Cannot find a library instance of "HereBeDragons-1.0".
Debug:
   (tail call): ?
   [C]: ?
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:446:
      ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:427
   (tail call): ?
Locals:
(*temporary) = <function> defined =[C]:-1
