### ISSUE TITLE
Icons on Minimap / World map does not dissapear

### ISSUE THREAD

**Issue by VerySvensk** [phanx-wow/HandyNotes_FieldPhotographer#5]
Hey!

The icons does not go away/Vanish once you take a picture of yourself with the Camera at the locations shown. They persist. 

Might be a problem with the print(IsQuestFlaggedCompleted ?

**Comment by Phanx** [comment]
Removed icons not disappearing from the minmap immediately is a long-standing issue with HandyNotes, and not a bug in this or any other plugin; there's nothing I can do about it, unfortunately. You'll see the same issue with other plugins, e.g. Draenor Treasures that removes icons when you loot treasures.
