### ISSUE TITLE
8.01 Lua Errors

### ISSUE THREAD

**Issue by MrsAngelD** [phanx-wow/HandyNotes_FieldPhotographer#6]
Message: ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:446: Cannot find a library instance of "HereBeDragons-1.0".
Time: Mon Jul 23 03:54:55 2018
Count: 1
Stack: ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:446: Cannot find a library instance of "HereBeDragons-1.0".
[C]: in function `error'
Interface\AddOns\Accountant\libs\LibStub\LibStub.lua:23: in function `LibStub'
...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:446: in function <...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:427>
(tail call): ?
Locals: (*temporary) = "Cannot find a library instance of "HereBeDragons-1.0"."

**Comment by Enigma-TL** [comment]
Same Error Here.
