### ISSUE TITLE
Error with BfA PrePatch

### ISSUE THREAD

**Issue by Naxterra** [phanx-wow/HandyNotes_FieldPhotographer#7]
WoW version: 8.0.1.27178
HandyNotes: Field Photographer version: 7.3.5.0

I am getting following error.
Date: 2018-07-29 18:14:25
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua line 446:
   Cannot find a library instance of "HereBeDragons-1.0".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:446:
      ...erface\AddOns\HandyNotes_FieldPhotographer\Addon.lua:427
   (tail call): ?
Locals:
(*temporary) = "Cannot find a library instance of "HereBeDragons-1.0"."

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  ACP, vr259 
  AngryAssignments, vv1.10.0
  Auctionator, v5.0.4
  BadBoy, vv8.0.7
  BadBoyCCleaner, vv8.0.0
  BadBoyLevels, vv8.0.0
  BagBrother, v
  Bagnon, v8.0.0
  Bartender4, v4.8.1
  DBMCore, v7.3.26
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  FishingBuddy, v1.9.6
  GatherMate2, v1.42.1
  Grail, v096
  GrailQuestsenUS, v27178
  GTFO, v4.46.1
  HandyNotes, vv1.5.2
  HandyNotesArgus, vv0.10
  HandyNotesBrokenShore, vv1.27
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.34
  HandyNotesFieldPhotographer, v7.3.5.0
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLunarFestival, vv1.5
  HandyNotesPandariaTreasures, v1.06
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleChests, v1.19
  HandyNotesWellRead, v8.0.0.0
  LeatrixPlus, v8.0.05
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.149
  NPCScan, v8.0.1.2
  Omen, v3.2.0
  OmniCC, v8.0.1
  Overachiever, v1.0.0
  Postal, vv3.6.0
  Prat30, vr1169      
  Prat30Libraries, v
  Quartz, v3.4.0
  RaidAchievement, v
  RaidAchievementOldModules, v
  RCLootCouncil, v2.8.2
  Recount, vv8.0.1a
  RSA, v452
  RSAWarlock, v
  SexyMap, vv8.0.3
  ShadowedUnitFrames, vv4.2.1
  SlideBar, v7.3.1 (<%codename%>)
  TidyPlatesThreatPlates, v9.0.7
  TipTac, v18.07.24
  TipTacItemRef, v18.07.22
  TipTacTalents, v18.07.19
  Titan, v5.14.1.80000
  TitanBag, v5.14.1.80000
  TitanClock, v5.14.1.80000
  TitanGold, v5.14.1.80000
  TitanLocation, v5.14.1.80000
  TitanLootType, v5.14.1.80000
  TitanPerformance, v5.14.1.80000
  TitanRepair, v5.14.1.80000
  TitanVolume, v5.14.1.80000
  TitanXP, v5.14.1.80000
  WeakAuras, v2.6.5
  WorldQuestsList, v67
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=70c)

**Comment by Phanx** [comment]
Update your addons. I already posted a new release yesterday.
